config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # root 'welcome#index'

  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  #resources :recipes
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe' 
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"  
  
  get '/signup2', to: 'chapters#chapter1_1'
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
  get '/chapter1_1', to: 'chapters#chapter1_1'
  get '/chapter1_2', to: 'chapters#chapter1_2'
  get '/chapter1_3', to: 'chapters#chapter1_3'
  get '/chapter1_4', to: 'chapters#chapter1_4'
  
  get '/chapter2_1', to: 'chapters#chapter2_1'
  get '/chapter2_2', to: 'chapters#chapter2_2'
  get '/chapter2_3', to: 'chapters#chapter2_3'
  
  get '/chapter3_1', to: 'chapters#chapter3_1'
  get '/chapter3_2', to: 'chapters#chapter3_2'
  
  get '/chapter4_1', to: 'chapters#chapter4_1'
  get '/chapter4_2', to: 'chapters#chapter4_2'
  get '/chapter4_3', to: 'chapters#chapter4_3'
  get '/chapter4_4', to: 'chapters#chapter4_4'
  get '/chapter4_5', to: 'chapters#chapter4_5'
  
  get '/chapter5_1', to: 'chapters#chapter5_1'
  get '/chapter5_2', to: 'chapters#chapter5_2'
  
  get '/chapter6_1', to: 'chapters#chapter6_1'
  get '/chapter6_2', to: 'chapters#chapter6_2'
  
  get '/chapter7_1', to: 'chapters#chapter7_1'
  get '/chapter7_2', to: 'chapters#chapter7_2'
  get '/chapter7_3', to: 'chapters#chapter7_3'
  
  get '/chapter8_1', to: 'chapters#chapter8_1'
  get '/chapter8_2', to: 'chapters#chapter8_2'
  
  get '/chapter9_1', to: 'chapters#chapter9_1'
  get '/chapter9_2', to: 'chapters#chapter9_2'
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients  
  has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Post was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Post was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Post deleted successfully"
    redirect_to recipes_path
  end
  
  private
  
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def recipe_params
      params.require(:recipe).permit(:name, :description, ingredient_ids: [])
    end
    
  def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own posts"
      redirect_to recipes_path
    end  
  end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", multipart: true, role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :Title %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :Description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter description" %>
        </div>
      </div>
 <!--     <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%#= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <%# cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <%# end %>
          </div>
        </div>
      </div>-->
<!--      <div class="form-group">
        <div class="control-label col-md-2">
          <%#= f.label :image, "Add Image" %>
        </div>
        <div class="col-md-8">
          <%#= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
      </div>-->
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Create Post", class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to posts listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%#= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      
      <!-- ingredients -->
      <!--<%# if recipe.ingredients.any? %>
        <p>Ingredients: <%#= render recipe.ingredients %></p>
      <%# end %>-->
      
      <p>
        <span class="quiet"><small>Created 
                  <%= time_ago_in_words(recipe.created_at) %> ago by 
                            <%= recipe.chef.chefname.capitalize %> | 
                    <%= pluralize(recipe.comments.count, 'Comment') %>
              </small></span>
      </p> 
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this post", edit_recipe_path(recipe), 
                  class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this post", recipe_path(recipe), 
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete this post?" },
                  class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing post" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Showing All Posts" %>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'recipe', obj: @recipes %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new post" %>


<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <!--<h4 class="center description"><strong>Steps: </strong></h4>
  <hr />-->
  <%= simple_format(@recipe.description) %>
  <hr />
<!-- ingerdien 
  <%# if @recipe.ingredients.any? %>
    <p>Ingredients: <%#= render @recipe.ingredients %></p>
  <%# end %> -->
  
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    
    <!--<p class="center">-->
      <%#= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    <!-- </p> -->
    
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit this post", edit_recipe_path(@recipe), 
          class: 'btn btn-xs btn-warning' %>
      <%= link_to "Delete this post", recipe_path(@recipe), method: :delete,
          data: { confirm: "Are you sure you want to delete?" },
          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to posts listing", recipes_path, 
        class: "btn btn-xs btn-primary" %>        
  </div>    
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", 
                                                role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", 
                                      placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", 
                              class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>


<% if @recipe.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>