config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # root 'welcome#index'

  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  #resources :recipes
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe' 
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"  
  
  get '/signup2', to: 'chapters#chapter1_1'
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
  get '/chapter1_1', to: 'chapters#chapter1_1'
  get '/chapter1_2', to: 'chapters#chapter1_2'
  get '/chapter1_3', to: 'chapters#chapter1_3'
  get '/chapter1_4', to: 'chapters#chapter1_4'
  
  get '/chapter2_1', to: 'chapters#chapter2_1'
  get '/chapter2_2', to: 'chapters#chapter2_2'
  get '/chapter2_3', to: 'chapters#chapter2_3'
  
  get '/chapter3_1', to: 'chapters#chapter3_1'
  get '/chapter3_2', to: 'chapters#chapter3_2'
  
  get '/chapter4_1', to: 'chapters#chapter4_1'
  get '/chapter4_2', to: 'chapters#chapter4_2'
  get '/chapter4_3', to: 'chapters#chapter4_3'
  get '/chapter4_4', to: 'chapters#chapter4_4'
  get '/chapter4_5', to: 'chapters#chapter4_5'
  
  get '/chapter5_1', to: 'chapters#chapter5_1'
  get '/chapter5_2', to: 'chapters#chapter5_2'
  
  get '/chapter6_1', to: 'chapters#chapter6_1'
  get '/chapter6_2', to: 'chapters#chapter6_2'
  
  get '/chapter7_1', to: 'chapters#chapter7_1'
  get '/chapter7_2', to: 'chapters#chapter7_2'
  get '/chapter7_3', to: 'chapters#chapter7_3'
  
  get '/chapter8_1', to: 'chapters#chapter8_1'
  get '/chapter8_2', to: 'chapters#chapter8_2'
  
  get '/chapter9_1', to: 'chapters#chapter9_1'
  get '/chapter9_2', to: 'chapters#chapter9_2'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
    Copyright &copy; 2017 Mike Dalton; All Rights Reserved.
  
  <nav>
    <ul>
      <li><%#= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
      data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" 
                                                aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Main", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
<!-- ================= start chapte list =============================== -->         
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
          role="button" aria-haspopup="true" aria-expanded="false">
          Menu
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Introduction", chapter1_1_path %></li>
            <li><%= link_to "Variables", chapter2_1_path %></li>
            <li><%= link_to "Conditional Statements", chapter3_1_path %></li>
            <li><%= link_to "Best Programming Practices", chapter4_1_path %></li>
            <li><%= link_to "While Loops", chapter5_1_path %></li>
            <li><%= link_to "For Loops", chapter6_1_path %></li>
            <li><%= link_to "Arrays", chapter7_1_path %></li>
            <li><%= link_to "Methods", chapter8_1_path %></li>
            <li><%= link_to "Strings", chapter9_1_path %></li>
          </ul>
<!-- =================== End chapte list =============================== -->        
        <li><%= link_to "All Posts", recipes_path %></li>
        <% if logged_in? %>
          <li><%= link_to "New Posts", new_recipe_path %></li>
          <li><%= link_to "Chat", chat_path %></li>
        <% end %>
        <!-- =============== display all user ================= -->
        <% if logged_in? && current_chef.admin? %>
           <li><%= link_to "User", chefs_path %></li>
        <% end %>
        <!-- ================================================== -->        
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.capitalize %>'s Profile 
                                <%= "Admin" if current_chef.admin? %> 
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", 
                                chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile", 
                                edit_chef_path(current_chef) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, 
                                      method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", login_path %></li>  
          <!--<li><#%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>-->
        <% end %>
        <li><%= link_to "Log Out user", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Log out chef", logout_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Java Tutorial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <br/><br/>
    <%= render 'layouts/messages' %>
    
    <div id="bg">
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    </div>
  </body>
</html>

app/views/layouts/application_Stripe.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PhotoApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
            <li class="col-md-8 user-name">
              <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,
                                                            edit_user_registration_path, title: 'Edit Profile' %>
            </li>
            <li class="col-md-1"> </li>
            <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
                                class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
            <li class="col-md-4 pull-right">
              <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
            </li>
            <% end %>
          </ul>          
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>